import Head from "next/head";
import Header from "../components/Header";
import MovieRow from "../components/MovieRow";

export default function Home({ trending100, coming25 }) {
  return (
    <main>
      <Head>
        <title>Dark Projector - Movies & Series</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <Header />
      <MovieRow category={trending100} title="Trending Movies" />
      <MovieRow category={coming25} title="Coming Soon" />
    </main>
  );
}

export async function getServerSideProps() {
  const trending = await fetch(
    `https://imdb-api.com/en/API/MostPopularMovies/${process.env.NEXT_PUBLIC_KEY_2}`
  );
  const coming = await fetch(
    `https://imdb-api.com/en/API/ComingSoon/${process.env.NEXT_PUBLIC_KEY_2}`
  );

  const trending100 = await trending.json();
  const coming25 = await coming.json();

  return { props: { trending100, coming25 } };
}
